spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName:
    username: postgres
    password: 123456

  mvc:
    pathmatching-strategy: ANT_PATH_MATCHER

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    locations:
      - filesystem:src/main/resources/db/migration