server:
  port: 8000
  mvc:
    pathmatching-strategy: ANT_PATH_MATCHER
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName:
    username: microservices
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  flyway:
#    locations:
#      - filesystem:src/main/resources/db/migration
#    outOfOrder: true
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

jwt:
  secret: secret